# For more information about all available options run fastlane action snapshot

devices([
   "iPhone 15 Pro Max",
   "iPhone 14 Plus",
   "iPad Pro (12.9-inch) (6th generation)",
   "iPad Pro (12.9-inch) (2nd generation)"
])

languages([
  "en-US"
])

scheme("ApollonSnapshotUITests")

output_directory("./screenshots")

clear_previous_screenshots(true)
override_status_bar(true)
skip_open_summary(true)
