# For more information about all available options run fastlane action snapshot

devices([
   "iPhone 13 Pro Max",
   "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US"
])

scheme("ApollonSnapshotUITests")

output_directory("./screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
